language: csharp
solution: RestfulBooker.sln
mono: none
dist: xenial
dotnet: 3.1

branches:
  only:
  - master
  - develop

install:
- dotnet restore RestfulBooker.sln
- nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner

script:
 - msbuild /p:Configuration=Release RestfulBooker.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe RestfulBooker.ApiTests/bin/Release/netcoreapp3.1/RestfulBooker.ApiTests.dll
 - dotnet build RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
 - dotnet test RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj

 before_install:
  - sudo apt-get install nunit-console
 before_script:
  - nuget restore RestfulBooker.sln
 after_script:
  - nunit-console RestfulBooker.ApiTests/bin/Release/netcoreapp3.1/RestfulBooker.ApiTests.dll
