language: csharp
mono: none
dist: bionic
dotnet: 3.1

branches:
  only:
  - master
  - develop

script:
 - dotnet restore
 - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
 - dotnet build RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
 - dotnet test RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
