language: csharp
mono: none
dist: bionic
dotnet: 3.1.100

branches:
  only:
  - master
  - develop

install:
- dotnet restore RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
- nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner

script:
 - dotnet build RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
 - dotnet test RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
