language: csharp
mono: none
dist: xenial
dotnet: 3.1.103

branches:
  only:
  - master
  - develop

install:
- dotnet restore
- nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner

script:
 - dotnet build
 - dotnet test RestfulBooker/RestfulBooker.ApiTests.csproj
