language: csharp
mono: none
dist: xenial
dotnet: 3.1.100

branches:
  only:
  - master
  - develop

install:
- dotnet restore RestfuBooker/RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
- nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner

script:
 - dotnet build RestfuBooker/RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
 - dotnet test RestfuBooker/RestfulBooker.ApiTests/RestfulBooker.ApiTests.csproj
