language: csharp
mono: none
dotnet: 3.1.0

install:
- dotnet restore
- nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner

script:
 - dotnet build
 - dotnet test RestfulBooker/RestfulBooker.ApiTests.csproj
